config-sparse:
  modules:
    aiSwapper:
        config: {}
    ucp2-legacy:
      config:
        o_firecooldown:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 3939
        o_onlyai:
          enabled:
            contents:
              suggested-value: true
        o_stop_player_keep_rotation:
          enabled:
            contents:
              suggested-value: true
        o_xtreme:
          enabled:
            contents:
              suggested-value: true
        o_change_siege_engine_spawn_position_catapult:
          enabled:
            contents:
              suggested-value: true
    startResources:
      config: {}
  plugins:
    Legends-Of-The-Orient-AI:
      config: {}
    AI-Tournament-Maps:
      config: {}
    ucp2-legacy-defaults:
      config: {}
meta:
  version: 1.0.0
